# mediawiki
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    apps: mediawiki
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: mediawiki-service
  selector:
    app: mediawiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        ports:
        - containerPort: 80
          name: mediawiki